# Generated by Django 5.0.9 on 2024-09-16 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_homepage_hero_image_homepage_body_and_more"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display as the background",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Background Image",
            ),
        ),
    ]
