# Generated by Django 5.0.9 on 2024-09-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homepage_background_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="image",
            new_name="hero_image",
        ),
    ]
