# Generated by Django 5.0.9 on 2024-09-20 20:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_homepage_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="head_body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
