# Generated by Django 5.1.2 on 2024-10-13 16:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_homepage_head_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body_color",
            field=colorfield.fields.ColorField(
                default="#000000",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Body Color",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="head_body_color",
            field=colorfield.fields.ColorField(
                default="#000000",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Head Body Color",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_color",
            field=colorfield.fields.ColorField(
                default="#000000",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Hero CTA Color",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_text_color",
            field=colorfield.fields.ColorField(
                default="#000000",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Hero Text Color",
            ),
        ),
    ]
