# Generated by Django 5.0.9 on 2024-10-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_gallerypage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="image_format",
            field=models.CharField(
                choices=[
                    ("square", "Square"),
                    ("landscape", "Landscape"),
                    ("portrait", "Portrait"),
                ],
                default="landscape",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="image_size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="layout",
            field=models.CharField(
                choices=[
                    ("grid", "Grid"),
                    ("masonry", "Masonry"),
                    ("slider", "Slider"),
                ],
                default="grid",
                max_length=50,
            ),
        ),
    ]
