# Generated by Django 5.0.9 on 2024-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_remove_gallerypage_gallery_images_galleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                max_length=50,
            ),
        ),
    ]
