# Generated by Django 5.0.9 on 2024-09-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings",
            name="mastodon_url",
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="Facebook URL"),
        ),
    ]
