# Generated by Django 5.0.9 on 2024-09-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_navigationsettings_mastodon_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="navigationsettings",
            old_name="github_url",
            new_name="facebook_url",
        ),
    ]
