# Generated by Django 5.0.9 on 2024-09-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_navigationsettings_facebook_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings",
            name="mastodon_url",
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="Facebook URL"),
        ),
    ]
