# Generated by Django 5.1.2 on 2024-10-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_rename_github_url_navigationsettings_facebook_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footertext",
            name="live",
            field=models.BooleanField(default=True),
        ),
    ]
